#*****************************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# dma_on_system.tcl: Tcl script for re-creating project 'sdio_recovery'
#
# Generated by Vivado on Fri Feb 20 14:29:11 +0300 2026
# IP Build 6138677 on Thu May 22 03:10:11 MDT 2025
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (dma_on_system.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "C:/Users/ykili/Desktop/Vivado/0_tutel/sdio_recovery/sdio_recovery.srcs/sources_1/new/debouncer.v"
#    "C:/Users/ykili/Desktop/Vivado/0_tutel/sdio_recovery/sdio_recovery.srcs/constrs_1/imports/constraint/Nexys-A7-100T-Master.xdc"
#    "C:/Users/ykili/Desktop/Vivado/0_tutel/sdio_recovery/sdio_recovery.srcs/utils_1/imports/synth_1/design_1_wrapper.dcp"
#
# 3. The following remote source files that were added to the original project:-
#
#    "C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/afifo.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/src/axi_dp_ram.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/src/axi_ram_rd_if.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/src/axi_ram_wr_if.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/src/axi_ram_wr_rd_if.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sdax_mm2s.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sdaxil.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sdckgen.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sdcmd.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sddma.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sddma_rxgears.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sddma_txgears.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sdfifo.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sdfrontend.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sdio.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sdio_top.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sdrxframe.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sdskid.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sdtxframe.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/xsdddr.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/xsdserdes8x.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sdax_s2mm.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/src/axi_ram_sdio_wrapper.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sddma_mm2s.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sddma_s2mm.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/llsdspi.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/spicmd.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/spirxdata.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/spitxdata.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sdspi.v"
#    "C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/exportspi.v"
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
 "[file normalize "$origin_dir/sdio_recovery.srcs/sources_1/new/debouncer.v"]"\
 "[file normalize "$origin_dir/sdio_recovery.srcs/constrs_1/imports/constraint/Nexys-A7-100T-Master.xdc"]"\
 "[file normalize "$origin_dir/sdio_recovery.srcs/utils_1/imports/synth_1/design_1_wrapper.dcp"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find local file $ifile "
      set status false
    }
  }

  set files [list \
 "[file normalize "$origin_dir/../../../sdio_test/hw/submodule/sdio/rtl/afifo.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/src/axi_dp_ram.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/src/axi_ram_rd_if.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/src/axi_ram_wr_if.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/src/axi_ram_wr_rd_if.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/submodule/sdio/rtl/sdax_mm2s.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/submodule/sdio/rtl/sdaxil.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/submodule/sdio/rtl/sdckgen.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/submodule/sdio/rtl/sdcmd.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/submodule/sdio/rtl/sddma.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/submodule/sdio/rtl/sddma_rxgears.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/submodule/sdio/rtl/sddma_txgears.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/submodule/sdio/rtl/sdfifo.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/submodule/sdio/rtl/sdfrontend.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/submodule/sdio/rtl/sdio.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/submodule/sdio/rtl/sdio_top.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/submodule/sdio/rtl/sdrxframe.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/submodule/sdio/rtl/sdskid.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/submodule/sdio/rtl/sdtxframe.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/submodule/sdio/rtl/xsdddr.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/submodule/sdio/rtl/xsdserdes8x.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/submodule/sdio/rtl/sdax_s2mm.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/src/axi_ram_sdio_wrapper.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/submodule/sdio/rtl/sddma_mm2s.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/submodule/sdio/rtl/sddma_s2mm.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/submodule/sdio/rtl/llsdspi.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/submodule/sdio/rtl/spicmd.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/submodule/sdio/rtl/spirxdata.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/submodule/sdio/rtl/spitxdata.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/submodule/sdio/rtl/sdspi.v"]"\
 "[file normalize "$origin_dir/../../../sdio_test/hw/submodule/sdio/rtl/exportspi.v"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find remote file $ifile "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "sdio_recovery"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "dma_on_system.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7a100tcsg324-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [current_project]
set_property -name "board_part_repo_paths" -value "[file normalize "$origin_dir/../../../../AppData/Roaming/Xilinx/Vivado/2025.1/xhub/board_store/xilinx_board_store"]" -objects $obj
set_property -name "board_part" -value "digilentinc.com:nexys-a7-100t:part0:1.3" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_resource_estimation" -value "0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "platform.board_id" -value "nexys-a7-100t" -objects $obj
set_property -name "revised_directory_structure" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "sim_compile_state" -value "1" -objects $obj
set_property -name "target_simulator" -value "ActiveHDL" -objects $obj
set_property -name "use_inline_hdl_ip" -value "1" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "28" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "28" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "28" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "28" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "28" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_FIFO XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/../../../sdio_test/hw/submodule/sdio/rtl/afifo.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/src/axi_dp_ram.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/src/axi_ram_rd_if.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/src/axi_ram_wr_if.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/src/axi_ram_wr_rd_if.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/submodule/sdio/rtl/sdax_mm2s.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/submodule/sdio/rtl/sdaxil.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/submodule/sdio/rtl/sdckgen.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/submodule/sdio/rtl/sdcmd.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/submodule/sdio/rtl/sddma.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/submodule/sdio/rtl/sddma_rxgears.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/submodule/sdio/rtl/sddma_txgears.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/submodule/sdio/rtl/sdfifo.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/submodule/sdio/rtl/sdfrontend.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/submodule/sdio/rtl/sdio.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/submodule/sdio/rtl/sdio_top.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/submodule/sdio/rtl/sdrxframe.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/submodule/sdio/rtl/sdskid.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/submodule/sdio/rtl/sdtxframe.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/submodule/sdio/rtl/xsdddr.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/submodule/sdio/rtl/xsdserdes8x.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/submodule/sdio/rtl/sdax_s2mm.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/src/axi_ram_sdio_wrapper.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/submodule/sdio/rtl/sddma_mm2s.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/submodule/sdio/rtl/sddma_s2mm.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/submodule/sdio/rtl/llsdspi.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/submodule/sdio/rtl/spicmd.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/submodule/sdio/rtl/spirxdata.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/submodule/sdio/rtl/spitxdata.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/submodule/sdio/rtl/sdspi.v"] \
 [file normalize "${origin_dir}/../../../sdio_test/hw/submodule/sdio/rtl/exportspi.v"] \
]
add_files -norecurse -fileset $obj $files

# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/sdio_recovery.srcs/sources_1/new/debouncer.v" ]\
]
set imported_files ""
foreach f $files {
  lappend imported_files [import_files -fileset sources_1 $f]
}

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../../../sdio_test/hw/submodule/sdio/rtl/sdax_s2mm.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "dataflow_viewer_settings" -value "min_width=16" -objects $obj
set_property -name "top" -value "design_1_wrapper" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "verilog_define" -value "SDIO_AXI=1" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize ${origin_dir}/sdio_recovery.srcs/constrs_1/imports/constraint/Nexys-A7-100T-Master.xdc]"
set file_imported [import_files -fileset constrs_1 [list $file]]
set file "constraint/Nexys-A7-100T-Master.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_constrs_file" -value "$proj_dir/${_xil_proj_name_}.srcs/constrs_1/imports/constraint/Nexys-A7-100T-Master.xdc" -objects $obj
set_property -name "target_ucf" -value "$proj_dir/${_xil_proj_name_}.srcs/constrs_1/imports/constraint/Nexys-A7-100T-Master.xdc" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "sim_wrapper_top" -value "1" -objects $obj
set_property -name "top" -value "sdspi" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/sdio_recovery.srcs/utils_1/imports/synth_1/design_1_wrapper.dcp" ]\
]
set imported_files ""
foreach f $files {
  lappend imported_files [import_files -fileset utils_1 $f]
}

# Set 'utils_1' fileset file properties for remote files
# None

# Set 'utils_1' fileset file properties for local files
set file "synth_1/design_1_wrapper.dcp"
set file_obj [get_files -of_objects [get_filesets utils_1] [list "*$file"]]
set_property -name "netlist_only" -value "0" -objects $file_obj


# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]


# Adding sources referenced in BDs, if not already added
if { [get_files [list afifo.v]] == "" } {
  import_files -quiet -fileset sources_1 C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/afifo.v
}
if { [get_files [list axi_dp_ram.v]] == "" } {
  import_files -quiet -fileset sources_1 C:/Users/ykili/Desktop/sdio_test/hw/src/axi_dp_ram.v
}
if { [get_files [list axi_ram_rd_if.v]] == "" } {
  import_files -quiet -fileset sources_1 C:/Users/ykili/Desktop/sdio_test/hw/src/axi_ram_rd_if.v
}
if { [get_files [list axi_ram_wr_if.v]] == "" } {
  import_files -quiet -fileset sources_1 C:/Users/ykili/Desktop/sdio_test/hw/src/axi_ram_wr_if.v
}
if { [get_files [list axi_ram_wr_rd_if.v]] == "" } {
  import_files -quiet -fileset sources_1 C:/Users/ykili/Desktop/sdio_test/hw/src/axi_ram_wr_rd_if.v
}
if { [get_files [list sdax_mm2s.v]] == "" } {
  import_files -quiet -fileset sources_1 C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sdax_mm2s.v
}
if { [get_files [list sdaxil.v]] == "" } {
  import_files -quiet -fileset sources_1 C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sdaxil.v
}
if { [get_files [list sdckgen.v]] == "" } {
  import_files -quiet -fileset sources_1 C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sdckgen.v
}
if { [get_files [list sdcmd.v]] == "" } {
  import_files -quiet -fileset sources_1 C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sdcmd.v
}
if { [get_files [list sddma.v]] == "" } {
  import_files -quiet -fileset sources_1 C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sddma.v
}
if { [get_files [list sddma_rxgears.v]] == "" } {
  import_files -quiet -fileset sources_1 C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sddma_rxgears.v
}
if { [get_files [list sddma_txgears.v]] == "" } {
  import_files -quiet -fileset sources_1 C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sddma_txgears.v
}
if { [get_files [list sdfifo.v]] == "" } {
  import_files -quiet -fileset sources_1 C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sdfifo.v
}
if { [get_files [list sdfrontend.v]] == "" } {
  import_files -quiet -fileset sources_1 C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sdfrontend.v
}
if { [get_files [list sdio.v]] == "" } {
  import_files -quiet -fileset sources_1 C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sdio.v
}
if { [get_files [list sdio_top.v]] == "" } {
  import_files -quiet -fileset sources_1 C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sdio_top.v
}
if { [get_files [list sdrxframe.v]] == "" } {
  import_files -quiet -fileset sources_1 C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sdrxframe.v
}
if { [get_files [list sdskid.v]] == "" } {
  import_files -quiet -fileset sources_1 C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sdskid.v
}
if { [get_files [list sdtxframe.v]] == "" } {
  import_files -quiet -fileset sources_1 C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sdtxframe.v
}
if { [get_files [list xsdddr.v]] == "" } {
  import_files -quiet -fileset sources_1 C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/xsdddr.v
}
if { [get_files [list xsdserdes8x.v]] == "" } {
  import_files -quiet -fileset sources_1 C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/xsdserdes8x.v
}
if { [get_files [list sdax_s2mm.v]] == "" } {
  import_files -quiet -fileset sources_1 C:/Users/ykili/Desktop/sdio_test/hw/submodule/sdio/rtl/sdax_s2mm.v
}
if { [get_files [list axi_ram_sdio_wrapper.v]] == "" } {
  import_files -quiet -fileset sources_1 C:/Users/ykili/Desktop/sdio_test/hw/src/axi_ram_sdio_wrapper.v
}


# Proc to create BD design_1
proc cr_bd_design_1 { parentCell } {
# The design that will be created by this Tcl proc contains the following 
# module references:
# axi_ram_sdio_wrapper



  # CHANGE DESIGN NAME HERE
  set design_name design_1

  common::send_gid_msg -ssname BD::TCL -id 2010 -severity "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK IPs
  ##################################################################
  set bCheckIPs 1
  if { $bCheckIPs == 1 } {
     set list_check_ips "\ 
  xilinx.com:ip:microblaze:11.0\
  xilinx.com:ip:mdm:3.2\
  xilinx.com:ip:clk_wiz:6.0\
  xilinx.com:ip:proc_sys_reset:5.0\
  xilinx.com:ip:axi_uartlite:2.0\
  xilinx.com:ip:smartconnect:1.0\
  xilinx.com:ip:util_vector_logic:2.0\
  xilinx.com:ip:lmb_v10:3.0\
  xilinx.com:ip:lmb_bram_if_cntlr:4.0\
  xilinx.com:ip:blk_mem_gen:8.4\
  "

   set list_ips_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2011 -severity "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2012 -severity "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

  }

  ##################################################################
  # CHECK Modules
  ##################################################################
  set bCheckModules 1
  if { $bCheckModules == 1 } {
     set list_check_mods "\ 
  axi_ram_sdio_wrapper\
  "

   set list_mods_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2020 -severity "INFO" "Checking if the following modules exist in the project's sources: $list_check_mods ."

   foreach mod_vlnv $list_check_mods {
      if { [can_resolve_reference $mod_vlnv] == 0 } {
         lappend list_mods_missing $mod_vlnv
      }
   }

   if { $list_mods_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2021 -severity "ERROR" "The following module(s) are not found in the project: $list_mods_missing" }
      common::send_gid_msg -ssname BD::TCL -id 2022 -severity "INFO" "Please add source files for the missing module(s) above."
      set bCheckIPsPassed 0
   }
}

  if { $bCheckIPsPassed != 1 } {
    common::send_gid_msg -ssname BD::TCL -id 2023 -severity "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }

  
# Hierarchical cell: microblaze_0_local_memory
proc create_hier_cell_microblaze_0_local_memory { parentCell nameHier } {

  variable script_folder

  if { $parentCell eq "" || $nameHier eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2092 -severity "ERROR" "create_hier_cell_microblaze_0_local_memory() - Empty argument(s)!"}
     return
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj

  # Create cell and set as current instance
  set hier_obj [create_bd_cell -type hier $nameHier]
  current_bd_instance $hier_obj

  # Create interface pins
  create_bd_intf_pin -mode MirroredMaster -vlnv xilinx.com:interface:lmb_rtl:1.0 DLMB

  create_bd_intf_pin -mode MirroredMaster -vlnv xilinx.com:interface:lmb_rtl:1.0 ILMB


  # Create pins
  create_bd_pin -dir I -type clk LMB_Clk
  create_bd_pin -dir I -type rst SYS_Rst

  # Create instance: dlmb_v10, and set properties
  set dlmb_v10 [ create_bd_cell -type ip -vlnv xilinx.com:ip:lmb_v10:3.0 dlmb_v10 ]

  # Create instance: ilmb_v10, and set properties
  set ilmb_v10 [ create_bd_cell -type ip -vlnv xilinx.com:ip:lmb_v10:3.0 ilmb_v10 ]

  # Create instance: dlmb_bram_if_cntlr, and set properties
  set dlmb_bram_if_cntlr [ create_bd_cell -type ip -vlnv xilinx.com:ip:lmb_bram_if_cntlr:4.0 dlmb_bram_if_cntlr ]
  set_property CONFIG.C_ECC {0} $dlmb_bram_if_cntlr


  # Create instance: ilmb_bram_if_cntlr, and set properties
  set ilmb_bram_if_cntlr [ create_bd_cell -type ip -vlnv xilinx.com:ip:lmb_bram_if_cntlr:4.0 ilmb_bram_if_cntlr ]
  set_property CONFIG.C_ECC {0} $ilmb_bram_if_cntlr


  # Create instance: lmb_bram, and set properties
  set lmb_bram [ create_bd_cell -type ip -vlnv xilinx.com:ip:blk_mem_gen:8.4 lmb_bram ]
  set_property -dict [list \
    CONFIG.Memory_Type {True_Dual_Port_RAM} \
    CONFIG.use_bram_block {BRAM_Controller} \
  ] $lmb_bram


  # Create interface connections
  connect_bd_intf_net -intf_net microblaze_0_dlmb [get_bd_intf_pins dlmb_v10/LMB_M] [get_bd_intf_pins DLMB]
  connect_bd_intf_net -intf_net microblaze_0_dlmb_bus [get_bd_intf_pins dlmb_v10/LMB_Sl_0] [get_bd_intf_pins dlmb_bram_if_cntlr/SLMB]
  connect_bd_intf_net -intf_net microblaze_0_dlmb_cntlr [get_bd_intf_pins dlmb_bram_if_cntlr/BRAM_PORT] [get_bd_intf_pins lmb_bram/BRAM_PORTA]
  connect_bd_intf_net -intf_net microblaze_0_ilmb [get_bd_intf_pins ilmb_v10/LMB_M] [get_bd_intf_pins ILMB]
  connect_bd_intf_net -intf_net microblaze_0_ilmb_bus [get_bd_intf_pins ilmb_v10/LMB_Sl_0] [get_bd_intf_pins ilmb_bram_if_cntlr/SLMB]
  connect_bd_intf_net -intf_net microblaze_0_ilmb_cntlr [get_bd_intf_pins ilmb_bram_if_cntlr/BRAM_PORT] [get_bd_intf_pins lmb_bram/BRAM_PORTB]

  # Create port connections
  connect_bd_net -net SYS_Rst_1  [get_bd_pins SYS_Rst] \
  [get_bd_pins dlmb_v10/SYS_Rst] \
  [get_bd_pins dlmb_bram_if_cntlr/LMB_Rst] \
  [get_bd_pins ilmb_v10/SYS_Rst] \
  [get_bd_pins ilmb_bram_if_cntlr/LMB_Rst]
  connect_bd_net -net microblaze_0_Clk  [get_bd_pins LMB_Clk] \
  [get_bd_pins dlmb_v10/LMB_Clk] \
  [get_bd_pins dlmb_bram_if_cntlr/LMB_Clk] \
  [get_bd_pins ilmb_v10/LMB_Clk] \
  [get_bd_pins ilmb_bram_if_cntlr/LMB_Clk]

  # Restore current instance
  current_bd_instance $oldCurInst
}
  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports
  set usb_uart [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:uart_rtl:1.0 usb_uart ]


  # Create ports
  set sys_clock [ create_bd_port -dir I -type clk -freq_hz 100000000 sys_clock ]
  set_property -dict [ list \
   CONFIG.PHASE {0.0} \
 ] $sys_clock
  set reset [ create_bd_port -dir I -type rst reset ]
  set_property -dict [ list \
   CONFIG.POLARITY {ACTIVE_LOW} \
 ] $reset
  set o_ck_0 [ create_bd_port -dir O o_ck_0 ]
  set io_cmd_0 [ create_bd_port -dir IO io_cmd_0 ]
  set io_dat_0 [ create_bd_port -dir IO -from 3 -to 0 io_dat_0 ]
  set i_card_detect_0 [ create_bd_port -dir I i_card_detect_0 ]
  set debug_aw_hit_0 [ create_bd_port -dir O debug_aw_hit_0 ]
  set debug_w_hit_0 [ create_bd_port -dir O debug_w_hit_0 ]
  set debug_ar_hit_0 [ create_bd_port -dir O debug_ar_hit_0 ]
  set debug_r_hit_0 [ create_bd_port -dir O debug_r_hit_0 ]

  # Create instance: microblaze_0, and set properties
  set microblaze_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:microblaze:11.0 microblaze_0 ]
  set_property -dict [list \
    CONFIG.C_DEBUG_ENABLED {1} \
    CONFIG.C_D_AXI {1} \
    CONFIG.C_D_LMB {1} \
    CONFIG.C_ENABLE_CONVERSION {0} \
    CONFIG.C_I_LMB {1} \
  ] $microblaze_0


  # Create instance: microblaze_0_local_memory
  create_hier_cell_microblaze_0_local_memory [current_bd_instance .] microblaze_0_local_memory

  # Create instance: mdm_1, and set properties
  set mdm_1 [ create_bd_cell -type ip -vlnv xilinx.com:ip:mdm:3.2 mdm_1 ]

  # Create instance: clk_wiz_1, and set properties
  set clk_wiz_1 [ create_bd_cell -type ip -vlnv xilinx.com:ip:clk_wiz:6.0 clk_wiz_1 ]
  set_property -dict [list \
    CONFIG.CLK_IN1_BOARD_INTERFACE {sys_clock} \
    CONFIG.PRIM_SOURCE {Single_ended_clock_capable_pin} \
    CONFIG.RESET_BOARD_INTERFACE {reset} \
    CONFIG.RESET_PORT {resetn} \
    CONFIG.RESET_TYPE {ACTIVE_LOW} \
    CONFIG.USE_BOARD_FLOW {true} \
  ] $clk_wiz_1


  # Create instance: rst_clk_wiz_1_100M, and set properties
  set rst_clk_wiz_1_100M [ create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 rst_clk_wiz_1_100M ]
  set_property -dict [list \
    CONFIG.RESET_BOARD_INTERFACE {reset} \
    CONFIG.USE_BOARD_FLOW {true} \
  ] $rst_clk_wiz_1_100M


  # Create instance: axi_uartlite_0, and set properties
  set axi_uartlite_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_uartlite:2.0 axi_uartlite_0 ]
  set_property -dict [list \
    CONFIG.UARTLITE_BOARD_INTERFACE {usb_uart} \
    CONFIG.USE_BOARD_FLOW {true} \
  ] $axi_uartlite_0


  # Create instance: axi_smc, and set properties
  set axi_smc [ create_bd_cell -type ip -vlnv xilinx.com:ip:smartconnect:1.0 axi_smc ]
  set_property -dict [list \
    CONFIG.NUM_MI {3} \
    CONFIG.NUM_SI {1} \
  ] $axi_smc


  # Create instance: util_vector_logic_0, and set properties
  set util_vector_logic_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:util_vector_logic:2.0 util_vector_logic_0 ]
  set_property -dict [list \
    CONFIG.C_OPERATION {not} \
    CONFIG.C_SIZE {1} \
  ] $util_vector_logic_0


  # Create instance: axi_ram_sdio_wrapper_0, and set properties
  set block_name axi_ram_sdio_wrapper
  set block_cell_name axi_ram_sdio_wrapper_0
  if { [catch {set axi_ram_sdio_wrapper_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $axi_ram_sdio_wrapper_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  set_property -dict [ list \
   CONFIG.POLARITY {ACTIVE_HIGH} \
 ] [get_bd_pins /axi_ram_sdio_wrapper_0/i_reset]

  # Create interface connections
  connect_bd_intf_net -intf_net axi_smc_M00_AXI [get_bd_intf_pins axi_smc/M00_AXI] [get_bd_intf_pins axi_uartlite_0/S_AXI]
  connect_bd_intf_net -intf_net axi_smc_M01_AXI [get_bd_intf_pins axi_ram_sdio_wrapper_0/S_AXIL] [get_bd_intf_pins axi_smc/M01_AXI]
  connect_bd_intf_net -intf_net axi_smc_M02_AXI [get_bd_intf_pins axi_smc/M02_AXI] [get_bd_intf_pins axi_ram_sdio_wrapper_0/s_axi_b]
  connect_bd_intf_net -intf_net axi_uartlite_0_UART [get_bd_intf_ports usb_uart] [get_bd_intf_pins axi_uartlite_0/UART]
  connect_bd_intf_net -intf_net microblaze_0_M_AXI_DP [get_bd_intf_pins microblaze_0/M_AXI_DP] [get_bd_intf_pins axi_smc/S00_AXI]
  connect_bd_intf_net -intf_net microblaze_0_debug [get_bd_intf_pins mdm_1/MBDEBUG_0] [get_bd_intf_pins microblaze_0/DEBUG]
  connect_bd_intf_net -intf_net microblaze_0_dlmb_1 [get_bd_intf_pins microblaze_0/DLMB] [get_bd_intf_pins microblaze_0_local_memory/DLMB]
  connect_bd_intf_net -intf_net microblaze_0_ilmb_1 [get_bd_intf_pins microblaze_0/ILMB] [get_bd_intf_pins microblaze_0_local_memory/ILMB]

  # Create port connections
  connect_bd_net -net Net  [get_bd_ports io_cmd_0] \
  [get_bd_pins axi_ram_sdio_wrapper_0/io_cmd]
  connect_bd_net -net Net1  [get_bd_ports io_dat_0] \
  [get_bd_pins axi_ram_sdio_wrapper_0/io_dat]
  connect_bd_net -net axi_ram_sdio_wrapper_0_debug_ar_hit  [get_bd_pins axi_ram_sdio_wrapper_0/debug_ar_hit] \
  [get_bd_ports debug_ar_hit_0]
  connect_bd_net -net axi_ram_sdio_wrapper_0_debug_aw_hit  [get_bd_pins axi_ram_sdio_wrapper_0/debug_aw_hit] \
  [get_bd_ports debug_aw_hit_0]
  connect_bd_net -net axi_ram_sdio_wrapper_0_debug_r_hit  [get_bd_pins axi_ram_sdio_wrapper_0/debug_r_hit] \
  [get_bd_ports debug_r_hit_0]
  connect_bd_net -net axi_ram_sdio_wrapper_0_debug_w_hit  [get_bd_pins axi_ram_sdio_wrapper_0/debug_w_hit] \
  [get_bd_ports debug_w_hit_0]
  connect_bd_net -net axi_ram_sdio_wrapper_0_o_ck  [get_bd_pins axi_ram_sdio_wrapper_0/o_ck] \
  [get_bd_ports o_ck_0]
  connect_bd_net -net axi_ram_sdio_wrapper_0_o_int  [get_bd_pins axi_ram_sdio_wrapper_0/o_int] \
  [get_bd_pins microblaze_0/Interrupt]
  connect_bd_net -net clk_wiz_1_locked  [get_bd_pins clk_wiz_1/locked] \
  [get_bd_pins rst_clk_wiz_1_100M/dcm_locked]
  connect_bd_net -net i_card_detect_0_1  [get_bd_ports i_card_detect_0] \
  [get_bd_pins util_vector_logic_0/Op1]
  connect_bd_net -net mdm_1_debug_sys_rst  [get_bd_pins mdm_1/Debug_SYS_Rst] \
  [get_bd_pins rst_clk_wiz_1_100M/mb_debug_sys_rst]
  connect_bd_net -net microblaze_0_Clk  [get_bd_pins clk_wiz_1/clk_out1] \
  [get_bd_pins microblaze_0/Clk] \
  [get_bd_pins microblaze_0_local_memory/LMB_Clk] \
  [get_bd_pins rst_clk_wiz_1_100M/slowest_sync_clk] \
  [get_bd_pins axi_smc/aclk] \
  [get_bd_pins axi_uartlite_0/s_axi_aclk] \
  [get_bd_pins axi_ram_sdio_wrapper_0/i_clk]
  connect_bd_net -net reset_1  [get_bd_ports reset] \
  [get_bd_pins clk_wiz_1/resetn] \
  [get_bd_pins rst_clk_wiz_1_100M/ext_reset_in]
  connect_bd_net -net rst_clk_wiz_1_100M_bus_struct_reset  [get_bd_pins rst_clk_wiz_1_100M/bus_struct_reset] \
  [get_bd_pins microblaze_0_local_memory/SYS_Rst]
  connect_bd_net -net rst_clk_wiz_1_100M_mb_reset  [get_bd_pins rst_clk_wiz_1_100M/mb_reset] \
  [get_bd_pins microblaze_0/Reset]
  connect_bd_net -net rst_clk_wiz_1_100M_peripheral_aresetn  [get_bd_pins rst_clk_wiz_1_100M/peripheral_aresetn] \
  [get_bd_pins axi_uartlite_0/s_axi_aresetn] \
  [get_bd_pins axi_smc/aresetn]
  connect_bd_net -net rst_clk_wiz_1_100M_peripheral_reset  [get_bd_pins rst_clk_wiz_1_100M/peripheral_reset] \
  [get_bd_pins axi_ram_sdio_wrapper_0/i_reset]
  connect_bd_net -net sys_clock_1  [get_bd_ports sys_clock] \
  [get_bd_pins clk_wiz_1/clk_in1]
  connect_bd_net -net util_vector_logic_0_Res  [get_bd_pins util_vector_logic_0/Res] \
  [get_bd_pins axi_ram_sdio_wrapper_0/i_card_detect]

  # Create address segments
  assign_bd_address -offset 0x00040000 -range 0x00001000 -target_address_space [get_bd_addr_spaces microblaze_0/Data] [get_bd_addr_segs axi_ram_sdio_wrapper_0/S_AXIL/reg0] -force
  assign_bd_address -offset 0x00050000 -range 0x00010000 -with_name SEG_axi_ram_sdio_wrapper_0_reg0_1 -target_address_space [get_bd_addr_spaces microblaze_0/Data] [get_bd_addr_segs axi_ram_sdio_wrapper_0/s_axi_b/reg0] -force
  assign_bd_address -offset 0x40600000 -range 0x00010000 -target_address_space [get_bd_addr_spaces microblaze_0/Data] [get_bd_addr_segs axi_uartlite_0/S_AXI/Reg] -force
  assign_bd_address -offset 0x00000000 -range 0x00040000 -target_address_space [get_bd_addr_spaces microblaze_0/Data] [get_bd_addr_segs microblaze_0_local_memory/dlmb_bram_if_cntlr/SLMB/Mem] -force
  assign_bd_address -offset 0x00000000 -range 0x00020000 -target_address_space [get_bd_addr_spaces microblaze_0/Instruction] [get_bd_addr_segs microblaze_0_local_memory/ilmb_bram_if_cntlr/SLMB/Mem] -force

  # Perform GUI Layout
  regenerate_bd_layout -layout_string {
   "ActiveEmotionalView":"Default View",
   "Default View_ScaleFactor":"1.02455",
   "Default View_TopLeft":"1180,40",
   "ExpandedHierarchyInLayout":"",
   "guistr":"# # String gsaved with Nlview 7.8.0 2024-04-26 e1825d835c VDI=44 GEI=38 GUI=JA:21.0
#  -string -flagsOSRD
preplace port usb_uart -pg 1 -lvl 6 -x 1850 -y 510 -defaultsOSRD
preplace port port-id_sys_clock -pg 1 -lvl 0 -x -10 -y 550 -defaultsOSRD
preplace port port-id_reset -pg 1 -lvl 0 -x -10 -y 520 -defaultsOSRD
preplace port port-id_o_ck_0 -pg 1 -lvl 6 -x 1850 -y 250 -defaultsOSRD
preplace port port-id_io_cmd_0 -pg 1 -lvl 6 -x 1850 -y 280 -defaultsOSRD
preplace port port-id_i_card_detect_0 -pg 1 -lvl 0 -x -10 -y 60 -defaultsOSRD
preplace port port-id_debug_aw_hit_0 -pg 1 -lvl 6 -x 1850 -y 110 -defaultsOSRD
preplace port port-id_debug_w_hit_0 -pg 1 -lvl 6 -x 1850 -y 140 -defaultsOSRD
preplace port port-id_debug_ar_hit_0 -pg 1 -lvl 6 -x 1850 -y 170 -defaultsOSRD
preplace port port-id_debug_r_hit_0 -pg 1 -lvl 6 -x 1850 -y 200 -defaultsOSRD
preplace portBus io_dat_0 -pg 1 -lvl 6 -x 1850 -y 310 -defaultsOSRD
preplace inst microblaze_0 -pg 1 -lvl 3 -x 880 -y 410 -defaultsOSRD
preplace inst microblaze_0_local_memory -pg 1 -lvl 4 -x 1320 -y 420 -defaultsOSRD
preplace inst mdm_1 -pg 1 -lvl 2 -x 400 -y 340 -defaultsOSRD
preplace inst clk_wiz_1 -pg 1 -lvl 1 -x 110 -y 540 -defaultsOSRD
preplace inst rst_clk_wiz_1_100M -pg 1 -lvl 2 -x 400 -y 510 -defaultsOSRD
preplace inst axi_uartlite_0 -pg 1 -lvl 5 -x 1660 -y 540 -defaultsOSRD
preplace inst axi_smc -pg 1 -lvl 4 -x 1320 -y 180 -defaultsOSRD
preplace inst util_vector_logic_0 -pg 1 -lvl 4 -x 1320 -y 60 -defaultsOSRD
preplace inst axi_ram_sdio_wrapper_0 -pg 1 -lvl 5 -x 1660 -y 280 -defaultsOSRD
preplace netloc Net 1 5 1 1820J 280n
preplace netloc Net1 1 5 1 1830J 310n
preplace netloc axi_ram_sdio_wrapper_0_o_ck 1 5 1 1810J 250n
preplace netloc axi_ram_sdio_wrapper_0_o_int 1 2 4 650 270 NJ 270 1470J 80 1800
preplace netloc clk_wiz_1_locked 1 1 1 N 550
preplace netloc i_card_detect_0_1 1 0 4 NJ 60 NJ 60 NJ 60 NJ
preplace netloc mdm_1_debug_sys_rst 1 1 2 230 410 570
preplace netloc microblaze_0_Clk 1 1 4 220 610 640 310 1160 280 1520
preplace netloc reset_1 1 0 2 20 470 200
preplace netloc rst_clk_wiz_1_100M_bus_struct_reset 1 2 2 590J 510 1180
preplace netloc rst_clk_wiz_1_100M_mb_reset 1 2 1 590 450n
preplace netloc rst_clk_wiz_1_100M_peripheral_aresetn 1 2 3 NJ 550 1170 560 NJ
preplace netloc rst_clk_wiz_1_100M_peripheral_reset 1 2 3 580 260 NJ 260 1480J
preplace netloc sys_clock_1 1 0 1 NJ 550
preplace netloc util_vector_logic_0_Res 1 4 1 1490J 60n
preplace netloc axi_ram_sdio_wrapper_0_debug_aw_hit 1 5 1 1810 110n
preplace netloc axi_ram_sdio_wrapper_0_debug_w_hit 1 5 1 1820 140n
preplace netloc axi_ram_sdio_wrapper_0_debug_ar_hit 1 5 1 1820 170n
preplace netloc axi_ram_sdio_wrapper_0_debug_r_hit 1 5 1 N 200
preplace netloc axi_smc_M00_AXI 1 4 1 1460 160n
preplace netloc axi_smc_M01_AXI 1 4 1 N 180
preplace netloc axi_smc_M02_AXI 1 4 1 N 200
preplace netloc axi_uartlite_0_UART 1 5 1 1830J 510n
preplace netloc microblaze_0_M_AXI_DP 1 3 1 1110 160n
preplace netloc microblaze_0_debug 1 2 1 590 330n
preplace netloc microblaze_0_dlmb_1 1 3 1 N 390
preplace netloc microblaze_0_ilmb_1 1 3 1 N 410
levelinfo -pg 1 -10 110 400 880 1320 1660 1850
pagesize -pg 1 -db -bbox -sgen -170 0 2000 620
"
}

  # Restore current instance
  current_bd_instance $oldCurInst

  validate_bd_design
  save_bd_design
  close_bd_design $design_name 
}
# End of cr_bd_design_1()

cr_bd_design_1 ""
set_property REGISTERED_WITH_MANAGER "1" [get_files design_1.bd ] 
set_property SYNTH_CHECKPOINT_MODE "Hierarchical" [get_files design_1.bd ] 

#call make_wrapper to create wrapper files
if { [get_property IS_LOCKED [ get_files -norecurse [list design_1.bd]] ] == 1  } {
  import_files -fileset sources_1 [file normalize "${origin_dir}/sdio_recovery.gen/sources_1/bd/design_1/hdl/design_1_wrapper.v" ]
} else {
  set wrapper_path [make_wrapper -fileset sources_1 -files [ get_files -norecurse [list design_1.bd]] -top]
  add_files -norecurse -fileset sources_1 $wrapper_path
}


set idrFlowPropertiesConstraints ""
catch {
 set idrFlowPropertiesConstraints [get_param runs.disableIDRFlowPropertyConstraints]
 set_param runs.disableIDRFlowPropertyConstraints 1
}

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7a100tcsg324-1 -flow {Vivado Synthesis 2025} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2025" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "incremental_checkpoint" -value "$proj_dir/${_xil_proj_name_}.srcs/utils_1/imports/synth_1/design_1_wrapper.dcp" -objects $obj
set_property -name "auto_incremental_checkpoint" -value "1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7a100tcsg324-1 -flow {Vivado Implementation 2025} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2025" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.routable_nets" -value "1" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]
catch {
 if { $idrFlowPropertiesConstraints != {} } {
   set_param runs.disableIDRFlowPropertyConstraints $idrFlowPropertiesConstraints
 }
}

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
