domain_path: C:\Users\ykili\Desktop\sdio_test\sw\sdio_test\export\sdio_test\sw\standalone_microblaze_0
app_src_dir: C:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
